# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/build/tools"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/dropgz"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/zapai"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  open-pull-requests-limit: 10
