name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          ascending: true
          close-issue-message: 'Issue closed due to inactivity.'
          close-pr-message: 'Pull request closed due to inactivity.'
          days-before-close: 7
          days-before-stale: 14
          delete-branch: true
          exempt-issue-labels: 'exempt-stale'
          operations-per-run: 100
          stale-issue-message: 'This issue is stale because it has been open for 2 weeks with no activity. Remove stale label or comment or this will be closed in 7 days'
          stale-pr-message: 'This pull request is stale because it has been open for 2 weeks with no activity. Remove stale label or comment or this will be closed in 7 days'
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
